version: '2'
services:

  # The Application
  app:
    build:
      context: ./dockerfiles/php7
      dockerfile: dockerfile
    working_dir: /var/www
    volumes:
    - ./:/var/www
    environment:
    - "DB_PORT=3306"
    - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./dockerfiles/nginx
      dockerfile: dockerfile
    working_dir: /var/www
    volumes_from:
    - app
    ports:
    - 8080:80

  # The Database
  database:
    image: mariadb:10.3.8
    volumes:
    - dbdata:/var/lib/mysql
    environment:
    - "MYSQL_DATABASE=homestead"
    - "MYSQL_USER=homestead"
    - "MYSQL_PASSWORD=secret"
    - "MYSQL_ROOT_PASSWORD=secret"
    ports:
    - "33061:3306"

    #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    volumes_from:
      - database
    environment:
      - "PMA_HOST=database"
      - "PMA_PORT:=3306"
    ports:
      - '4000:80'
    depends_on:
      - database

volumes:
  dbdata: